(()=>{"use strict";
const BUILD_ID="live-free-2026.08.21.2";
const APP_BASE="/Gold-Mine/";
const DATA_URL="https://raw.githubusercontent.com/umarvandutch/Gold-Mine/main/live-data.json";
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const weights={rates:45,inflation:28,labour:22,growth:18,consumer:12,business:10,trade:9,housing:8,government:7,other:5};
const categoryLabels={rates:"Fed / rates",inflation:"Inflation",labour:"Jobs",growth:"Growth",consumer:"Consumer",business:"Business activity",trade:"Trade",housing:"Housing",government:"Government / bonds",other:"Other US data"};
const categoryMeaning={rates:"Interest rates affect the return available on cash and bonds. Higher expected US rates usually support the dollar and yields, which can pressure gold.",inflation:"Inflation affects what the Fed may do with interest rates. Hotter inflation can keep rates higher for longer; cooler inflation can make rate cuts more likely.",labour:"Jobs data shows how strong the US labour market is. A very strong jobs market can keep wage and inflation pressure alive; weakness can increase expectations for rate cuts.",growth:"GDP and growth data show whether the US economy is expanding or slowing. Stronger growth can support the dollar and yields; weaker growth can do the opposite.",consumer:"US consumers drive a large part of the economy. Strong spending and confidence can support growth and rates; weakness can point to a slowdown.",business:"PMIs, ISM, production and regional business surveys show how companies are doing. Stronger activity can support the dollar; weaker activity can increase slowdown concerns.",trade:"Trade data can affect growth and the dollar, but its gold impact is often smaller than Fed, inflation or jobs news.",housing:"Housing reacts strongly to interest rates and helps show whether tighter borrowing costs are slowing the economy.",government:"Treasury auctions, budgets and government data can affect yields, but the direction is often more nuanced than a simple good/bad surprise.",other:"This is still monitored, but its direct effect on the dollar and gold is normally smaller or less predictable."};
const demoEvents=[
{id:"demo-cpi",dateUtc:new Date(Date.now()-3600000).toISOString(),name:"US CPI y/y",actual:3.6,consensus:3.4,previous:3.3,unit:"%",volatility:"HIGH",category:"inflation",source:"Fallback sample"},
{id:"demo-nfp",dateUtc:new Date(Date.now()-7200000).toISOString(),name:"Non-Farm Payrolls",actual:175,consensus:238,previous:303,unit:"K",volatility:"HIGH",category:"labour",source:"Fallback sample"},
{id:"demo-fomc",dateUtc:new Date(Date.now()-10800000).toISOString(),name:"FOMC Rate Decision",actual:5.5,consensus:5.5,previous:5.5,unit:"%",volatility:"HIGH",category:"rates",source:"Fallback sample"}
];
let data={generatedAt:null,calendarStatus:"fallback",events:demoEvents,market:{},headlines:[],isFallback:true};

function parseNum(v){if(v===null||v===undefined||v==="")return null;const m=String(v).replace(/,/g,"").match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null}
function valueText(v,unit){if(v===null||v===undefined||v==="")return"—";const s=String(v);if(!unit||/[A-Za-z%$€£¥]/.test(s))return s;return`${s}${unit}`}
function categoryFor(e){
 if(e.category&&weights[e.category]!==undefined)return e.category;
 const s=String(e.name||"").toLowerCase();
 if(/fomc|interest rate|fed funds|federal reserve|powell|beige book|jackson hole|fed chair|fed governor|fed president|fed official|fed policymaker|fed minutes|fed meeting|fed rate|fed's /.test(s))return"rates";
 if(/cpi|pce|ppi|inflation|price index|prices paid|prices received|personal consumption expenditures price/.test(s))return"inflation";
 if(/payroll|employment|unemployment|jobless|jolts|job openings|labor|labour|wage|earnings|employment cost/.test(s))return"labour";
 if(/gdp|growth rate|gross domestic product/.test(s))return"growth";
 if(/retail|consumer confidence|consumer sentiment|consumer expectations|personal spending|personal income|consumer spending/.test(s))return"consumer";
 if(/housing|home sales|building permits|mortgage|construction|housing starts/.test(s))return"housing";
 if(/pmi|ism|industrial production|factory|durable|capital goods|business|manufacturing|services|philadelphia fed|dallas fed|richmond fed|kansas city fed|empire state/.test(s))return"business";
 if(/trade|export|import|current account/.test(s))return"trade";
 if(/treasury|auction|budget|government/.test(s))return"government";
 return"other";
}
function impactFor(e){const v=String(e.volatility||"NONE").toUpperCase(),c=categoryFor(e),n=String(e.name||"").toLowerCase();if(c==="rates"&&(v==="HIGH"||/fomc|rate decision|powell|jackson hole/.test(n)))return"critical";if(v==="HIGH")return"high";if(v==="MEDIUM")return"medium";return"low"}
function impactMultiplier(e){return({critical:1,high:.82,medium:.56,low:.3})[impactFor(e)]||.3}
function higherIsUsdNegative(name){const s=String(name||"").toLowerCase();return/unemployment rate|jobless claims|continuing claims|job cuts|trade deficit|layoffs/.test(s)}
function ambiguousEvent(e){const s=String(e.name||"").toLowerCase();return e.isSpeech||/speech|speaks|auction|inventory|inventories|stocks change|storage change|rig count|net positions|cftc|budget balance|mortgage rate|oil stocks|gasoline stocks|distillate stocks|heating oil/.test(s)}
function eventUsdDirection(e){if(ambiguousEvent(e))return 0;const a=parseNum(e.actual),c=parseNum(e.consensus);if(a===null||c===null)return 0;const gap=a-c,scale=Math.max(Math.abs(c)*.1,.1);let d=clamp(gap/scale,-1,1);if(higherIsUsdNegative(e.name))d*=-1;return d}
function eventGoldScore(e){const d=eventUsdDirection(e);if(!d)return 0;const age=Math.max(0,(Date.now()-new Date(e.dateUtc).getTime())/36e5),recency=clamp(1-age/96,.25,1);return-d*(weights[categoryFor(e)]||5)*impactMultiplier(e)*recency}
function directionInfo(e){const d=eventUsdDirection(e);if(d>.12)return{usd:"USD likely stronger",gold:"Gold pressure",cls:"usd-up",arrow:"Gold ↓"};if(d<-.12)return{usd:"USD likely weaker",gold:"Gold support",cls:"usd-down",arrow:"Gold ↑"};return{usd:"Direction unclear",gold:"Wait for confirmation",cls:"neutral",arrow:"Mixed"}}
function surpriseText(e){const a=parseNum(e.actual),c=parseNum(e.consensus);if(a===null)return"The actual result is not available yet.";if(c===null)return"The result is out, but there is no consensus figure in the free feed, so the surprise cannot be measured reliably.";const tol=Math.max(Math.abs(c)*.005,.0001);if(Math.abs(a-c)<=tol)return"The result was broadly in line with what economists expected.";return a>c?"The result came in above economists’ consensus forecast.":"The result came in below economists’ consensus forecast."}
function beginnerEffect(e){const d=eventUsdDirection(e),c=categoryFor(e);if(ambiguousEvent(e))return"This release is useful context, but its number does not have a reliable one-direction relationship with USD and gold, so Gold Mine does not force a signal from it.";if(!d&&c==="rates")return"For Fed decisions, the headline rate is only part of the story. The statement, projections and Powell’s guidance can matter more than an unchanged rate.";if(d>.12)return"First reaction: this leans USD-positive. If the dollar and US yields also rise, that is normally a headwind for gold.";if(d<-.12)return"First reaction: this leans USD-negative. If the dollar and US yields also fall, that is normally supportive for gold.";return"There is no clean first-order signal from the numbers alone. Gold Mine keeps it in context but does not force a bullish or bearish call."}
function formatTimes(iso){const d=new Date(iso);if(Number.isNaN(d.getTime()))return{local:"Date/time unavailable",et:""};const opts={weekday:"short",day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit",timeZoneName:"short"};const local=new Intl.DateTimeFormat(undefined,opts).format(d);const et=new Intl.DateTimeFormat("en-US",{...opts,timeZone:"America/New_York"}).format(d);return{local,et}}
function relativeTime(iso){if(!iso)return"—";const ms=Date.now()-new Date(iso).getTime();if(ms<0)return"just scheduled";const m=Math.floor(ms/60000);if(m<1)return"just now";if(m<60)return`${m} min ago`;const h=Math.floor(m/60);if(h<24)return`${h} hr${h===1?"":"s"} ago`;return`${Math.floor(h/24)} day${Math.floor(h/24)===1?"":"s"} ago`}
function impactBadge(i){const l=i==="critical"?"Critical":i==="high"?"High":i==="medium"?"Medium":"Low";return`<span class="impact-badge ${i}">${l}</span>`}

function renderReleases(filter="all"){
 const now=Date.now();
 let events=(data.events||[]).filter(e=>e.dateUtc&&new Date(e.dateUtc).getTime()<=now&&e.actual!==null&&e.actual!==undefined).sort((a,b)=>new Date(b.dateUtc)-new Date(a.dateUtc));
 if(filter!=="all")events=events.filter(e=>filter==="rates"?categoryFor(e)==="rates":impactFor(e)===filter);
 const list=document.getElementById("releaseList");
 if(!events.length){list.innerHTML='<div class="empty-card"><strong>No completed releases in this view yet.</strong><span>Upcoming events are in the Calendar tab.</span></div>';return}
 list.innerHTML=events.slice(0,30).map(e=>{const d=directionInfo(e),t=formatTimes(e.dateUtc),cat=categoryFor(e),imp=impactFor(e);return`<article class="release-card ${imp}" data-release="${encodeURIComponent(e.id)}" tabindex="0" role="button"><div class="release-top"><div class="release-title"><span class="eyebrow">${categoryLabels[cat].toUpperCase()}</span><h3>${escapeHtml(e.name)}</h3><p><strong>${escapeHtml(t.local)}</strong><br>${escapeHtml(t.et)} · New York</p></div>${impactBadge(imp)}</div><div class="release-values"><div class="metric"><span>Actual</span><strong>${escapeHtml(valueText(e.actual,e.unit))}</strong></div><div class="metric"><span>Consensus</span><strong>${escapeHtml(valueText(e.consensus,e.unit))}</strong></div><div class="metric"><span>Previous</span><strong>${escapeHtml(valueText(e.previous,e.unit))}</strong></div></div><div class="release-summary"><span class="direction-tag ${d.cls}">${d.arrow}</span><p><strong>${escapeHtml(surpriseText(e))}</strong> ${escapeHtml(beginnerEffect(e))}</p></div></article>`}).join("");
 list.querySelectorAll("[data-release]").forEach(c=>{const open=()=>openDetail(decodeURIComponent(c.dataset.release));c.addEventListener("click",open);c.addEventListener("keydown",ev=>{if(ev.key==="Enter"||ev.key===" "){ev.preventDefault();open()}})})
}
function renderCalendar(){const now=Date.now(),events=(data.events||[]).filter(e=>e.dateUtc&&new Date(e.dateUtc).getTime()>now).sort((a,b)=>new Date(a.dateUtc)-new Date(b.dateUtc)).slice(0,60),box=document.getElementById("calendarList");if(!events.length){box.innerHTML='<div class="empty-card"><strong>No upcoming US events loaded.</strong><span>The free collector may still be refreshing. Try again shortly.</span></div>';return}box.innerHTML=events.map(e=>{const t=formatTimes(e.dateUtc),cat=categoryFor(e);return`<div class="timeline-item"><div class="timeline-marker"></div><div class="timeline-card"><div class="line-one"><div><span class="eyebrow">${categoryLabels[cat].toUpperCase()}</span><strong>${escapeHtml(e.name)}</strong></div>${impactBadge(impactFor(e))}</div><p class="calendar-time"><b>${escapeHtml(t.local)}</b><br>${escapeHtml(t.et)} · New York</p><p>${escapeHtml(categoryMeaning[cat])}</p></div></div>`}).join("")}

function headlineSignal(h){const s=String(h.title||"").toLowerCase();let score=0,reason="Context only";if(/higher for longer|hawkish|rate hike|rates.*higher|inflation.*elevated|not.*cut|delay.*cut/.test(s)){score=-4;reason="Could support USD/yields and pressure gold"}else if(/dovish|rate cut|cut rates|easing|lower rates/.test(s)){score=4;reason="Could reduce yields/USD and support gold"}else if(/inflation.*(rise|rises|accelerat|hotter|surge)|prices.*(rise|surge)/.test(s)){score=-3;reason="Hotter inflation can keep rates higher"}else if(/inflation.*(cool|ease|slow|fall)/.test(s)){score=3;reason="Cooling inflation can support rate-cut expectations"}else if(/recession|jobs.*weaken|unemployment.*rise|layoffs.*rise|economy.*slow/.test(s)){score=2.5;reason="Growth weakness can pull yields/USD lower"}else if(/war|attack|conflict|geopolit|sanctions|crisis/.test(s)){score=2;reason="Risk-off stress can create safe-haven demand for gold"}return{score,reason}}
function renderNews(){const list=document.getElementById("newsList"),heads=(data.headlines||[]).slice(0,20);if(!heads.length){list.innerHTML='<div class="empty-card"><strong>No live headlines loaded yet.</strong><span>The official/public news feeds are still refreshing.</span></div>';return}list.innerHTML=heads.map(h=>{const t=h.publishedUtc?formatTimes(h.publishedUtc):{local:"Time unavailable",et:""},s=headlineSignal(h),cls=s.score>0?"bullish":s.score<0?"bearish":"neutral",tag=s.score>0?"Gold-supportive context":s.score<0?"Gold-negative context":"Context only";return`<a class="news-card" href="${escapeAttr(h.url||"#")}" target="_blank" rel="noopener noreferrer"><div class="news-top"><span class="eyebrow">${escapeHtml(categoryLabels[h.category]||"Macro news")}</span><span class="news-signal ${cls}">${tag}</span></div><strong>${escapeHtml(h.title)}</strong><p>${escapeHtml(t.local)} · ${escapeHtml(h.source||"Public news")}</p><small>${escapeHtml(s.reason)}</small></a>`}).join("")}

function marketDrivers(){
 const m=data.market||{},out=[];
 if(m.dxy&&Number.isFinite(m.dxy.changePct))out.push({name:"US Dollar Index (DXY)",detail:`${fmtSigned(m.dxy.changePct)}% vs previous close`,score:clamp(-m.dxy.changePct/.55,-1,1)*18});
 if(m.us2y&&Number.isFinite(m.us2y.deltaBps))out.push({name:"US 2Y Treasury yield",detail:`${fmtSigned(m.us2y.deltaBps)} bps vs prior Treasury day`,score:clamp(-m.us2y.deltaBps/12,-1,1)*10});
 if(m.us10y&&Number.isFinite(m.us10y.deltaBps))out.push({name:"US 10Y Treasury yield",detail:`${fmtSigned(m.us10y.deltaBps)} bps vs prior Treasury day`,score:clamp(-m.us10y.deltaBps/10,-1,1)*7});
 if(m.real10y&&Number.isFinite(m.real10y.deltaBps))out.push({name:"US 10Y real yield",detail:`${fmtSigned(m.real10y.deltaBps)} bps vs prior Treasury day`,score:clamp(-m.real10y.deltaBps/10,-1,1)*11});
 if(m.xau&&Number.isFinite(m.xau.changePct))out.push({name:"Gold market confirmation",detail:`${fmtSigned(m.xau.changePct)}% vs previous close`,score:clamp(m.xau.changePct/1,-1,1)*6});
 return out;
}
function prediction(){const now=Date.now(),events=(data.events||[]).filter(e=>e.dateUtc&&new Date(e.dateUtc).getTime()<=now&&now-new Date(e.dateUtc).getTime()<72*36e5&&e.actual!==null&&e.actual!==undefined);const eventDrivers=events.map(e=>({name:e.name,detail:`${valueText(e.actual,e.unit)} actual vs ${valueText(e.consensus,e.unit)} consensus · ${categoryLabels[categoryFor(e)]}`,score:eventGoldScore(e)})).filter(d=>Math.abs(d.score)>.25);const newsDrivers=(data.headlines||[]).map(h=>{const s=headlineSignal(h);return{name:`News: ${h.title}`,detail:s.reason,score:s.score}}).filter(d=>Math.abs(d.score)>.2).sort((a,b)=>Math.abs(b.score)-Math.abs(a.score)).slice(0,8);const newsTotal=clamp(newsDrivers.reduce((a,d)=>a+d.score,0),-15,15);const mkt=marketDrivers();const all=[...eventDrivers,...mkt];let total=all.reduce((a,d)=>a+d.score,0)+newsTotal;if(newsTotal)all.push({name:"Broader news context",detail:"Net effect from clearly directional macro headlines",score:newsTotal});const meaningful=all.filter(d=>Math.abs(d.score)>.8),bull=meaningful.filter(d=>d.score>0).length,bear=meaningful.filter(d=>d.score<0).length,agreement=meaningful.length?Math.max(bull,bear)/meaningful.length:.5,maxAbs=all.reduce((a,d)=>a+Math.abs(d.score),0)||1,mag=clamp(Math.abs(total)/maxAbs,0,1),coverage=clamp((eventDrivers.length?1:0)+(mkt.length>=2?1:0)+(newsDrivers.length?1:0),0,3)/3,strength=Math.round(clamp(25+agreement*35+mag*25+coverage*15,0,95));let stance="WAIT",bias="Neutral / mixed",cls="neutral";if(total>12){stance="BULLISH BIAS";bias="Evidence currently leans supportive for XAUUSD";cls="bullish"}if(total<-12){stance="BEARISH BIAS";bias="Evidence currently leans negative for XAUUSD";cls="bearish"}return{total,strength,stance,bias,cls,drivers:all.sort((a,b)=>Math.abs(b.score)-Math.abs(a.score)).slice(0,8),eventCount:eventDrivers.length,newsCount:newsDrivers.length,marketCount:mkt.length}}
function scoreClass(s){return s>1?"bullish":s<-1?"bearish":"neutral"}function scoreText(s){return s>1?"Gold +":s<-1?"Gold −":"Mixed"}
function renderPrediction(){const p=prediction(),angle=Math.round(p.strength*3.6),m=data.market||{};document.getElementById("predictionPanel").innerHTML=`<div class="prediction-hero"><div class="bias-line"><div><span class="bias-label">Current evidence-based view</span><div class="bias-value ${p.cls}">${p.stance}</div></div><div class="score-ring" style="--score-angle:${angle}deg"><div><strong>${p.strength}</strong><span>Evidence<br>strength</span></div></div></div><p class="prediction-sub"><strong>${p.bias}.</strong> This combines ${p.eventCount} recent scored US release${p.eventCount===1?"":"s"}, ${p.newsCount} clearly directional headline${p.newsCount===1?"":"s"} and ${p.marketCount} available market confirmation${p.marketCount===1?"":"s"}.</p><div class="beginner-callout"><strong>Beginner shortcut</strong><span>Gold often struggles when the US dollar and real/nominal yields rise. Gold often benefits when they fall — but safe-haven demand can sometimes override that relationship.</span></div><div class="horizon-strip"><span>Immediate reaction</span><span>1–4 hour follow-through</span><span>Reassess if USD/yields reverse</span></div></div><div class="analysis-card"><span class="eyebrow">WHAT IS DRIVING THE VIEW</span><h3>Strongest evidence right now</h3>${p.drivers.length?p.drivers.map(d=>`<div class="driver"><div class="driver-copy"><strong>${escapeHtml(d.name)}</strong><span>${escapeHtml(d.detail)}</span></div><span class="driver-score ${scoreClass(d.score)}">${scoreText(d.score)}</span></div>`).join(""):'<div class="empty-card"><strong>Not enough live evidence yet.</strong><span>Gold Mine will stay neutral rather than invent a signal.</span></div>'}${marketGrid(m)}</div><div class="scenario-card"><span class="eyebrow">WHAT WOULD CHANGE THE VIEW?</span><h3>Simple invalidation guide</h3><div class="scenario bear"><strong>Gold bearish</strong><p>Stronger-than-expected US data + hawkish Fed + rising DXY/yields is the clearest negative cluster.</p></div><div class="scenario"><strong>Mixed / wait</strong><p>Data points disagree, or the dollar and yields fail to confirm the headline surprise.</p></div><div class="scenario bull"><strong>Gold bullish</strong><p>Weaker US data + dovish Fed + falling DXY/yields is the clearest supportive cluster. Risk-off shocks can also support gold.</p></div></div><p class="disclaimer">Educational rough guideline only. Free feeds can be delayed or incomplete. Evidence strength is not a win probability, target guarantee or financial advice.</p>`}
function marketGrid(m){const vals=Object.values(m||{}).filter(Boolean);if(!vals.length)return'<p class="section-help">No free market confirmation is available right now.</p>';return`<div class="market-grid">${vals.map(x=>`<div class="market-tile"><span>${escapeHtml(x.label||x.name||"Market")}</span><strong>${escapeHtml(String(x.price??"—"))}</strong><small>${Number.isFinite(x.changePct)?`${fmtSigned(x.changePct)}% vs prev close`:Number.isFinite(x.deltaBps)?`${fmtSigned(x.deltaBps)} bps vs prior day`:"Free snapshot"}${x.date?` · ${escapeHtml(x.date)}`:""}</small></div>`).join("")}</div>`}

function openDetail(id){const e=(data.events||[]).find(x=>String(x.id)===String(id));if(!e)return;const t=formatTimes(e.dateUtc),cat=categoryFor(e),d=directionInfo(e);document.getElementById("detailContent").innerHTML=`<div class="detail-head"><span class="eyebrow">${categoryLabels[cat].toUpperCase()}</span><h2 id="detailTitle">${escapeHtml(e.name)}</h2><p>${escapeHtml(t.local)}<br>${escapeHtml(t.et)} · New York · ${escapeHtml(e.source||"US calendar")}</p></div><div class="detail-metrics"><div class="metric"><span>Actual</span><strong>${escapeHtml(valueText(e.actual,e.unit))}</strong></div><div class="metric"><span>Consensus</span><strong>${escapeHtml(valueText(e.consensus,e.unit))}</strong></div><div class="metric"><span>Previous</span><strong>${escapeHtml(valueText(e.previous,e.unit))}</strong></div></div><div class="detail-section"><strong>In plain English: what happened?</strong><p>${escapeHtml(surpriseText(e))}</p></div><div class="detail-section"><strong>Why does this matter?</strong><p>${escapeHtml(categoryMeaning[cat])}</p></div><div class="detail-section"><strong>Likely first effect on USD</strong><p><span class="direction-tag ${d.cls}">${escapeHtml(d.usd)}</span> ${escapeHtml(beginnerEffect(e))}</p></div><div class="detail-section weight-callout"><strong>What could it mean for gold?</strong><p><b>${escapeHtml(d.gold)}.</b> This is only the first-order macro effect. Gold Mine also checks other releases, headlines and available dollar/yield confirmation before forming the overall XAUUSD bias.</p></div><div class="detail-section"><strong>Important caveat</strong><p>Markets can react differently if the result was already priced in, if revisions changed the story, or if another major event happened at the same time. That is why one release never becomes an automatic trade instruction.</p></div>`;document.getElementById("detailOverlay").hidden=false;document.body.style.overflow="hidden"}
function closeDetail(){document.getElementById("detailOverlay").hidden=true;document.body.style.overflow=""}
function fmtSigned(n){return`${n>0?"+":""}${Number(n).toFixed(Math.abs(n)>=10?1:2)}`}
function escapeHtml(s){return String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
function escapeAttr(s){return escapeHtml(s).replace(/`/g,"&#96;")}
function setState(id,ok,label){const el=document.getElementById(id);if(!el)return;el.textContent=label;el.classList.toggle("success",!!ok);el.classList.toggle("warning",!ok)}
function updateStatus(){const live=data.calendarStatus==="live"&&!data.isFallback,age=data.generatedAt?relativeTime(data.generatedAt):"unknown",counts=data.counts||{};const banner=document.getElementById("modeBanner"),title=document.getElementById("dataStatusTitle"),text=document.getElementById("dataStatusText"),pill=document.getElementById("livePill");if(live){banner.classList.add("live");title.textContent="Live US data connected";text.textContent=`${counts.events??(data.events||[]).length} US calendar events + ${counts.headlines??(data.headlines||[]).length} macro headlines · refreshed ${age}. Free feeds can be delayed.`;pill.innerHTML='<span></span> Live data'}else{banner.classList.remove("live");title.textContent="Live feed temporarily unavailable";text.textContent="Showing clearly-labelled fallback samples while the free collector retries. No sample number is treated as live.";pill.innerHTML='<span></span> Fallback'}setState("calendarState",live,live?"Live":"Fallback");setState("newsState",(data.headlines||[]).length>0,(data.headlines||[]).length?"Live":"Waiting");setState("marketState",Object.values(data.market||{}).some(Boolean),Object.values(data.market||{}).some(Boolean)?"Free / daily":"Waiting");document.getElementById("lastRefresh").textContent=data.generatedAt?`${formatTimes(data.generatedAt).local} (${age})`:"—"}
function renderAll(){renderReleases(document.querySelector(".chip.active")?.dataset.filter||"all");renderCalendar();renderNews();renderPrediction();updateStatus();document.getElementById("buildId").textContent=BUILD_ID}
async function loadLiveData(){try{const r=await fetch(`${DATA_URL}?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();if(Array.isArray(j.events)&&j.events.length){data={...j,isFallback:false};renderAll();return}}catch(e){console.warn("Live data unavailable",e)}if(!data||!Array.isArray(data.events)||!data.events.length)data={generatedAt:null,calendarStatus:"fallback",events:demoEvents,market:{},headlines:[],isFallback:true};renderAll()}

document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>{const n=b.dataset.view;document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${n}`));window.scrollTo({top:0,behavior:"auto"})}));
document.querySelectorAll(".chip").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".chip").forEach(x=>x.classList.toggle("active",x===b));renderReleases(b.dataset.filter||"all")}));
document.querySelectorAll("[data-close-detail]").forEach(e=>e.addEventListener("click",closeDetail));document.getElementById("recalcButton").addEventListener("click",()=>{loadLiveData();renderPrediction()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDetail()});
let deferredInstall=null;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;const b=document.getElementById("installButton");b.hidden=false;b.addEventListener("click",async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;b.hidden=true},{once:true})});
if("serviceWorker"in navigator){navigator.serviceWorker.register("./sw.js",{scope:APP_BASE}).then(r=>{r.update().catch(()=>{});setInterval(()=>r.update().catch(()=>{}),9e5)}).catch(()=>{});let refreshing=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(refreshing)return;refreshing=true;location.reload()})}
renderAll();loadLiveData();setInterval(loadLiveData,60000);
})();
