(()=>{
"use strict";
let latest=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const attr=s=>esc(s).replace(/`/g,"&#96;");
const categoryLabels={rates:"Fed / rates",inflation:"Inflation",labour:"Jobs",growth:"Growth",consumer:"Consumer",business:"Business activity",trade:"Trade",housing:"Housing",government:"Government / bonds",other:"Macro news"};
function categoryFor(x){if(x?.category)return x.category;const s=String(x?.name||x?.title||"").toLowerCase();if(/fomc|fed|powell|rate/.test(s))return"rates";if(/cpi|pce|ppi|inflation|price/.test(s))return"inflation";if(/payroll|employment|unemployment|jobless|jolts|wage/.test(s))return"labour";if(/gdp|growth/.test(s))return"growth";if(/retail|consumer/.test(s))return"consumer";if(/pmi|ism|manufacturing|services|industrial/.test(s))return"business";if(/housing|home|mortgage|building permits/.test(s))return"housing";if(/treasury|auction|budget/.test(s))return"government";if(/trade|export|import/.test(s))return"trade";return"other"}
function impactFor(e){const v=String(e?.volatility||e?.impact||"").toUpperCase(),c=categoryFor(e),n=String(e?.name||e?.title||"").toLowerCase();if(c==="rates"&&(v==="HIGH"||/fomc|rate decision|powell/.test(n)))return"critical";if(v==="HIGH")return"high";if(v==="MEDIUM")return"medium";return"low"}
function badge(i){const l=i==="critical"?"Critical":i==="high"?"High":i==="medium"?"Medium":"Low";return`<span class="impact-badge ${i}">${l}</span>`}
function times(v){const d=new Date(v||"");if(Number.isNaN(d.getTime()))return{local:"Time unavailable",et:""};const o={weekday:"short",day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZoneName:"short"};return{local:new Intl.DateTimeFormat(undefined,o).format(d),et:new Intl.DateTimeFormat("en-US",{...o,timeZone:"America/New_York"}).format(d)}}
function headlineContext(h){const s=String(h?.title||"").toLowerCase();if(/higher for longer|hawkish|rate hike|inflation.*(hot|rise|surge)|yield.*rise|dollar.*rise/.test(s))return{cls:"bearish",tag:"Gold-negative context",reason:"May support USD/yields and pressure gold."};if(/dovish|rate cut|easing|inflation.*(cool|ease|fall)|yield.*fall|dollar.*fall/.test(s))return{cls:"bullish",tag:"Gold-supportive context",reason:"May reduce USD/yield pressure and support gold."};if(/war|attack|sanction|geopolit|crisis|recession/.test(s))return{cls:"bullish",tag:"Risk-event context",reason:"May increase safe-haven demand, but confirmation is still required."};return{cls:"neutral",tag:"Context only",reason:"Use with live price, USD and yield confirmation."}}
function renderNews(){const list=document.getElementById("newsList");if(!list||!latest)return;const heads=(Array.isArray(latest.headlines)?latest.headlines:[]).filter(h=>h?.title).sort((a,b)=>Date.parse(b.publishedUtc||0)-Date.parse(a.publishedUtc||0)).slice(0,30);if(!heads.length){list.innerHTML='<div class="empty-card"><strong>No live headlines returned.</strong><span>The live backend returned zero usable headlines. Use Refresh all live and check the data status.</span></div>';return}list.innerHTML=heads.map(h=>{const t=times(h.publishedUtc),ctx=headlineContext(h),cat=categoryFor(h);return`<a class="news-card" href="${attr(h.url||"#")}" target="_blank" rel="noopener noreferrer"><div class="news-top"><span class="eyebrow">${esc(categoryLabels[cat]||"Macro news")}</span><span class="news-signal ${ctx.cls}">${esc(ctx.tag)}</span></div><strong>${esc(h.title)}</strong><p>${esc(t.local)} · ${esc(h.source||"Live public news")}</p><small>${esc(ctx.reason)}</small></a>`}).join("")}
function renderCalendar(){const box=document.getElementById("calendarList");if(!box||!latest)return;const now=Date.now(),events=(Array.isArray(latest.events)?latest.events:[]).filter(e=>{const t=Date.parse(e?.dateUtc||"");return Number.isFinite(t)&&t>now}).sort((a,b)=>Date.parse(a.dateUtc)-Date.parse(b.dateUtc)).slice(0,60);if(!events.length){box.innerHTML='<div class="empty-card"><strong>No upcoming US events returned.</strong><span>The current backend snapshot has no future medium/high-impact events.</span></div>';return}box.innerHTML=events.map(e=>{const t=times(e.dateUtc),cat=categoryFor(e),imp=impactFor(e);return`<div class="timeline-item"><div class="timeline-marker"></div><div class="timeline-card"><div class="line-one"><div><span class="eyebrow">${esc(categoryLabels[cat]||"US macro")}</span><strong>${esc(e.name||"US economic event")}</strong></div>${badge(imp)}</div><p class="calendar-time"><b>${esc(t.local)}</b><br>${esc(t.et)} · New York</p></div></div>`}).join("")}
function renderReleaseRefresh(){const list=document.getElementById("releaseList");if(!list||!latest)return;const activeFilter=document.querySelector(".chip.active")?.dataset.filter||"all",now=Date.now();let events=(Array.isArray(latest.events)?latest.events:[]).filter(e=>{const t=Date.parse(e?.dateUtc||"");return Number.isFinite(t)&&t<=now&&e.actual!==null&&e.actual!==undefined}).sort((a,b)=>Date.parse(b.dateUtc)-Date.parse(a.dateUtc));if(activeFilter!=="all")events=events.filter(e=>activeFilter==="rates"?categoryFor(e)==="rates":impactFor(e)===activeFilter);if(!events.length)return;list.innerHTML=events.slice(0,30).map(e=>{const t=times(e.dateUtc),imp=impactFor(e),cat=categoryFor(e);const f=v=>v===null||v===undefined||v===""?"—":`${v}${e.unit&&!String(v).includes(e.unit)?e.unit:""}`;return`<article class="release-card ${imp}"><div class="release-top"><div class="release-title"><span class="eyebrow">${esc(categoryLabels[cat]||"US macro")}</span><h3>${esc(e.name||"US release")}</h3><p><strong>${esc(t.local)}</strong><br>${esc(t.et)} · New York</p></div>${badge(imp)}</div><div class="release-values"><div class="metric"><span>Actual</span><strong>${esc(f(e.actual))}</strong></div><div class="metric"><span>Consensus</span><strong>${esc(f(e.consensus))}</strong></div><div class="metric"><span>Previous</span><strong>${esc(f(e.previous))}</strong></div></div></article>`}).join("")}
function sourceLabel(){if(!latest)return"";if(latest._goldMineSource==="worker"||latest.collectorMode==="cloudflare-true-live"||latest?.sourceStatus?.worker==="true-live")return"TRUE LIVE";return"BACKUP SNAPSHOT"}
function apply(data){if(!data||!Array.isArray(data.events))return;latest=data;window.GoldMineLiveSnapshot=data;renderNews();renderCalendar();renderReleaseRefresh();const newsState=document.getElementById("newsState");if(newsState){const n=Array.isArray(data.headlines)?data.headlines.length:0;newsState.textContent=n?`${sourceLabel()} · ${n}`:"No headlines";newsState.classList.toggle("success",n>0);newsState.classList.toggle("warning",n===0)}}
window.addEventListener("goldmine-snapshot-updated",e=>apply(e.detail));
window.addEventListener("goldmine-signals-updated",e=>{if(e.detail&&!latest)apply(e.detail)});
if(window.GoldMineLiveSnapshot)apply(window.GoldMineLiveSnapshot);
})();
