(()=>{
"use strict";
let latest=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const attr=s=>esc(s).replace(/`/g,"&#96;");
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const categoryLabels={rates:"Fed / rates",inflation:"Inflation",labour:"Jobs",growth:"Growth",consumer:"Consumer",business:"Business activity",trade:"Trade",housing:"Housing",government:"Government / bonds",other:"Macro news"};
function categoryFor(x){if(x?.category)return x.category;const s=String(x?.name||x?.title||"").toLowerCase();if(/fomc|fed|powell|rate/.test(s))return"rates";if(/cpi|pce|ppi|inflation|price/.test(s))return"inflation";if(/payroll|employment|unemployment|jobless|jolts|wage/.test(s))return"labour";if(/gdp|growth/.test(s))return"growth";if(/retail|consumer/.test(s))return"consumer";if(/pmi|ism|manufacturing|services|industrial/.test(s))return"business";if(/housing|home|mortgage|building permits/.test(s))return"housing";if(/treasury|auction|budget/.test(s))return"government";if(/trade|export|import/.test(s))return"trade";return"other"}
function impactFor(e){const v=String(e?.volatility||e?.impact||"").toUpperCase(),c=categoryFor(e),n=String(e?.name||e?.title||"").toLowerCase();if(c==="rates"&&(v==="HIGH"||/fomc|rate decision|powell/.test(n)))return"critical";if(v==="HIGH")return"high";if(v==="MEDIUM")return"medium";return"low"}
function badge(i){const l=i==="critical"?"Critical":i==="high"?"High":i==="medium"?"Medium":"Low";return`<span class="impact-badge ${i}">${l}</span>`}
function times(v){const d=new Date(v||"");if(Number.isNaN(d.getTime()))return{uk:"Time unavailable",us:"Time unavailable"};const common={weekday:"short",day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",timeZoneName:"short"};return{uk:new Intl.DateTimeFormat("en-GB",{...common,timeZone:"Europe/London",hour12:false}).format(d),us:new Intl.DateTimeFormat("en-US",{...common,timeZone:"America/New_York",hour12:true}).format(d)}}
function timeBlock(v,label="Release"){const t=times(v);return`<div class="gm-time-grid"><div><span>${label} · UK</span><strong>${esc(t.uk)}</strong></div><div><span>${label} · US (ET)</span><strong>${esc(t.us)}</strong></div></div>`}
function higherIsUsdNegative(name){return/unemployment rate|jobless claims|continuing claims|job cuts|trade deficit|layoffs/i.test(String(name||""))}
function eventSimple(e){const cat=categoryFor(e),a=num(e?.actual),c=num(e?.consensus),name=e?.name||"This US release",past=Date.parse(e?.dateUtc||0)<=Date.now(),surprise=a!==null&&c!==null?a-c:null;let meaning="This is a US economic update that traders compare with expectations.";let gold="Gold usually reacts through changes in the US dollar, bond yields and expectations for Federal Reserve policy.";let watch="Watch the actual figure versus consensus, then check whether DXY and Treasury yields confirm the first move.";
  if(cat==="rates"){meaning="This affects expectations for Federal Reserve interest rates. The statement, projections and Fed commentary can matter as much as the headline rate.";gold="Higher-for-longer rate expectations can support the dollar/yields and pressure gold; easier policy expectations can support gold.";watch="Watch the policy wording, Powell/Fed guidance, DXY and US yields rather than relying on the rate number alone."}
  else if(cat==="inflation"){meaning="This measures US price pressure. Markets use it to judge whether inflation is cooling or staying too high.";gold="Hotter inflation can keep rate expectations and yields higher, often pressuring gold. Cooler inflation can do the opposite.";watch="Compare actual versus forecast, then check DXY and real/nominal yields for confirmation."}
  else if(cat==="labour"){meaning="This shows the strength of the US jobs market, including hiring, unemployment, wages or claims.";gold="A stronger labour market can support higher rates and the dollar; weaker labour data can increase easing expectations and support gold.";watch="Look at the whole jobs picture, especially payrolls, unemployment and wage growth together."}
  else if(cat==="growth"||cat==="business"||cat==="consumer"){meaning="This is a read on US economic activity and demand.";gold="Stronger growth can support the dollar and yields; weaker activity can support rate-cut expectations, although risk-off flows can complicate the reaction.";watch="Compare the surprise with consensus and confirm the reaction in DXY, yields and XAUUSD structure."}
  else if(cat==="government"){meaning="This can influence Treasury supply, yields or fiscal expectations.";gold="The gold effect is usually indirect through yields, the dollar and broader risk sentiment.";watch="Treat it as context unless yields and the dollar move clearly in the same direction."}
  if(past&&surprise!==null){const higher=surprise>0,usdPositive=higherIsUsdNegative(name)?!higher:higher;meaning+=` The reported figure was ${Math.abs(surprise)<1e-9?"roughly in line with":higher?"above":"below"} consensus.`;gold+=usdPositive?" The first-order surprise leans USD-positive/gold-negative, but market confirmation still matters.":" The first-order surprise leans USD-negative/gold-supportive, but market confirmation still matters."}
  return{meaning,gold,watch};
}
function headlineContext(h){const s=String(h?.title||"").toLowerCase();if(/higher for longer|hawkish|rate hike|inflation.*(hot|rise|surge)|yield.*rise|dollar.*rise/.test(s))return{cls:"bearish",tag:"Gold-negative context",reason:"This wording may support US rates/yields or the dollar, which can pressure gold.",watch:"Check whether DXY and Treasury yields actually rise; if they do not, avoid forcing a bearish gold interpretation."};if(/dovish|rate cut|easing|inflation.*(cool|ease|fall)|yield.*fall|dollar.*fall/.test(s))return{cls:"bullish",tag:"Gold-supportive context",reason:"This wording may reduce rate/yield or dollar pressure and support gold.",watch:"Check whether DXY and yields fall and whether XAUUSD confirms with price structure."};if(/war|attack|sanction|geopolit|crisis|recession/.test(s))return{cls:"bullish",tag:"Risk-event context",reason:"This can increase safe-haven demand for gold, although the dollar can also strengthen in risk-off markets.",watch:"Watch gold and DXY together because safe-haven flows can make the usual inverse relationship break down."};return{cls:"neutral",tag:"Context only",reason:"The headline matters, but its direct gold direction is not clear enough to force a signal.",watch:"Use it as context and wait for price, DXY and yields to confirm direction."}}
function simpleNews(h){const cat=categoryFor(h),ctx=headlineContext(h);let what="This headline is part of the macro backdrop Gold Mine monitors.";if(cat==="rates")what="This is mainly about Federal Reserve policy or interest-rate expectations.";else if(cat==="inflation")what="This is mainly about inflation and what it could mean for future Fed policy.";else if(cat==="labour")what="This is mainly about US employment and labour-market strength.";else if(cat==="growth"||cat==="business"||cat==="consumer")what="This is mainly about the strength or weakness of the US economy.";return{what,why:ctx.reason,watch:ctx.watch,ctx}}
function detailsBody({what,why,watch,url,source}){return`<div class="gm-simple"><div><span>In simple terms</span><p>${esc(what)}</p></div><div><span>Why gold cares</span><p>${esc(why)}</p></div><div><span>What to watch next</span><p>${esc(watch)}</p></div>${url?`<a class="text-button gm-source-link" href="${attr(url)}" target="_blank" rel="noopener noreferrer">Open source${source?` · ${esc(source)}`:""}</a>`:""}</div>`}
function renderNews(){const list=document.getElementById("newsList");if(!list||!latest)return;const heads=(Array.isArray(latest.headlines)?latest.headlines:[]).filter(h=>h?.title).sort((a,b)=>Date.parse(b.publishedUtc||0)-Date.parse(a.publishedUtc||0)).slice(0,30);if(!heads.length){list.innerHTML='<div class="empty-card"><strong>No live headlines returned.</strong><span>The live backend returned zero usable headlines. Use Refresh all live and check the data status.</span></div>';return}list.innerHTML=heads.map(h=>{const n=simpleNews(h),cat=categoryFor(h);return`<details class="gm-expand news-card"><summary><div class="news-top"><span class="eyebrow">${esc(categoryLabels[cat]||"Macro news")}</span><span class="news-signal ${n.ctx.cls}">${esc(n.ctx.tag)}</span></div><strong>${esc(h.title)}</strong>${timeBlock(h.publishedUtc,"Published")}<small>${esc(h.source||"Live public news")} · Tap to understand this news</small></summary>${detailsBody({what:n.what,why:n.why,watch:n.watch,url:h.url,source:h.source})}</details>`}).join("")}
function eventDetails(e){const x=eventSimple(e),cat=categoryFor(e),imp=impactFor(e);return`<details class="gm-expand timeline-card"><summary><div class="line-one"><div><span class="eyebrow">${esc(categoryLabels[cat]||"US macro")}</span><strong>${esc(e.name||"US economic event")}</strong></div>${badge(imp)}</div>${timeBlock(e.dateUtc,"Release")}<small>Tap for a simple explanation</small></summary>${detailsBody({what:x.meaning,why:x.gold,watch:x.watch})}</details>`}
function renderCalendar(){const box=document.getElementById("calendarList");if(!box||!latest)return;const now=Date.now(),events=(Array.isArray(latest.events)?latest.events:[]).filter(e=>{const t=Date.parse(e?.dateUtc||"");return Number.isFinite(t)&&t>now}).sort((a,b)=>Date.parse(a.dateUtc)-Date.parse(b.dateUtc)).slice(0,50),heads=(Array.isArray(latest.headlines)?latest.headlines:[]).filter(h=>{const t=Date.parse(h?.publishedUtc||"");return h?.title&&Number.isFinite(t)&&now-t<=36*3600000&&t<=now}).sort((a,b)=>Date.parse(b.publishedUtc)-Date.parse(a.publishedUtc)).slice(0,12);let html='<div class="gm-calendar-section"><span class="eyebrow">UPCOMING RELEASES</span><h3>UK & US release times</h3></div>';if(events.length)html+=events.map(e=>`<div class="timeline-item"><div class="timeline-marker"></div>${eventDetails(e)}</div>`).join("");else html+='<div class="empty-card"><strong>No upcoming US events returned.</strong><span>The current backend snapshot has no future medium/high-impact events.</span></div>';html+='<div class="gm-calendar-section recent"><span class="eyebrow">RECENT MACRO NEWS</span><h3>News in the calendar</h3><p>Published headlines are shown here too so you can expand them in simple terms.</p></div>';if(heads.length)html+=heads.map(h=>{const n=simpleNews(h),cat=categoryFor(h);return`<div class="timeline-item gm-news-timeline"><div class="timeline-marker"></div><details class="gm-expand timeline-card"><summary><div class="line-one"><div><span class="eyebrow">NEWS · ${esc(categoryLabels[cat]||"Macro")}</span><strong>${esc(h.title)}</strong></div><span class="news-signal ${n.ctx.cls}">${esc(n.ctx.tag)}</span></div>${timeBlock(h.publishedUtc,"Published")}<small>${esc(h.source||"Public news")} · Tap for simple terms</small></summary>${detailsBody({what:n.what,why:n.why,watch:n.watch,url:h.url,source:h.source})}</details></div>`}).join("");else html+='<div class="empty-card"><strong>No recent macro headlines loaded.</strong></div>';box.innerHTML=html}
function renderReleaseRefresh(){const list=document.getElementById("releaseList");if(!list||!latest)return;const activeFilter=document.querySelector(".chip.active")?.dataset.filter||"all",now=Date.now();let events=(Array.isArray(latest.events)?latest.events:[]).filter(e=>{const t=Date.parse(e?.dateUtc||"");return Number.isFinite(t)&&t<=now&&e.actual!==null&&e.actual!==undefined}).sort((a,b)=>Date.parse(b.dateUtc)-Date.parse(a.dateUtc));if(activeFilter!=="all")events=events.filter(e=>activeFilter==="rates"?categoryFor(e)==="rates":impactFor(e)===activeFilter);if(!events.length){list.innerHTML='<div class="empty-card"><strong>No completed releases in this view yet.</strong></div>';return}list.innerHTML=events.slice(0,30).map(e=>{const imp=impactFor(e),cat=categoryFor(e),x=eventSimple(e),f=v=>v===null||v===undefined||v===""?"—":`${v}${e.unit&&!String(v).includes(e.unit)?e.unit:""}`;return`<details class="gm-expand release-card ${imp}"><summary><div class="release-top"><div class="release-title"><span class="eyebrow">${esc(categoryLabels[cat]||"US macro")}</span><h3>${esc(e.name||"US release")}</h3></div>${badge(imp)}</div>${timeBlock(e.dateUtc,"Released")}<div class="release-values"><div class="metric"><span>Actual</span><strong>${esc(f(e.actual))}</strong></div><div class="metric"><span>Consensus</span><strong>${esc(f(e.consensus))}</strong></div><div class="metric"><span>Previous</span><strong>${esc(f(e.previous))}</strong></div></div><small>Tap for a simple explanation</small></summary>${detailsBody({what:x.meaning,why:x.gold,watch:x.watch})}</details>`}).join("")}
function sourceLabel(){if(!latest)return"";if(latest._goldMineSource==="worker"||latest.collectorMode==="cloudflare-true-live"||latest?.sourceStatus?.worker==="true-live")return"TRUE LIVE";return"BACKUP SNAPSHOT"}
function apply(data){if(!data||!Array.isArray(data.events))return;latest=data;window.GoldMineLiveSnapshot=data;renderNews();renderCalendar();renderReleaseRefresh();const newsState=document.getElementById("newsState");if(newsState){const n=Array.isArray(data.headlines)?data.headlines.length:0;newsState.textContent=n?`${sourceLabel()} · ${n}`:"No headlines";newsState.classList.toggle("success",n>0);newsState.classList.toggle("warning",n===0)}}
function style(){if(document.getElementById("gm-live-ui-v4-style"))return;const s=document.createElement("style");s.id="gm-live-ui-v4-style";s.textContent=`.gm-expand{display:block}.gm-expand>summary{list-style:none;cursor:pointer}.gm-expand>summary::-webkit-details-marker{display:none}.gm-expand>summary:after{content:"＋";float:right;margin-top:8px;font-weight:800;color:#8b6a22}.gm-expand[open]>summary:after{content:"−"}.gm-time-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:9px 0}.gm-time-grid>div{background:#f7f6f2;border-radius:9px;padding:8px}.gm-time-grid span{display:block;font-size:8px;color:#777;text-transform:uppercase}.gm-time-grid strong{display:block;font-size:10px;margin-top:3px}.gm-simple{border-top:1px solid #ece7dd;margin-top:10px;padding-top:10px;display:grid;gap:8px}.gm-simple>div{background:#faf9f6;border-radius:10px;padding:9px}.gm-simple span{font-size:8.5px;font-weight:800;text-transform:uppercase;color:#8a6a28}.gm-simple p{font-size:10.5px;line-height:1.5;margin:4px 0 0}.gm-source-link{display:inline-block;width:max-content}.gm-calendar-section{margin:10px 0 12px}.gm-calendar-section h3{margin:3px 0}.gm-calendar-section p{font-size:10.5px;color:#70757d}.gm-calendar-section.recent{margin-top:24px}.gm-news-timeline .timeline-marker{background:#b49145}@media(max-width:640px){.gm-time-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
window.addEventListener("goldmine-snapshot-updated",e=>apply(e.detail));window.addEventListener("goldmine-signals-updated",e=>{if(e.detail&&!latest)apply(e.detail)});style();if(window.GoldMineLiveSnapshot)apply(window.GoldMineLiveSnapshot);
})();
