(()=>{
  "use strict";
  const GITHUB="https://raw.githubusercontent.com/umarvandutch/Gold-Mine/main/live-data.json";
  let data=null,busy=false,timer=null;
  const worker=()=>String(window.GOLD_MINE_CONFIG?.liveWorkerUrl||"").trim();
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const ageMin=v=>{if(!v)return 99999;const n=new Date(v).getTime();return Number.isFinite(n)?Math.max(0,(Date.now()-n)/60000):99999};
  const fmt=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString()};
  const signed=v=>`${Number(v||0)>=0?"+":""}${Number(v||0).toFixed(2)}`;
  const active=()=>document.getElementById("view-signals")?.classList.contains("active");

  function installUI(){if(!document.getElementById("view-signals")){const settings=document.getElementById("view-settings"),section=document.createElement("section");section.id="view-signals";section.className="view";section.innerHTML='<div class="section-heading"><div><span class="eyebrow">STRICT 4H EXECUTION FILTER</span><h2>Buy & sell limit signals</h2></div><button id="signalsRefresh" class="text-button">Refresh signals live</button></div><div id="signalsPanel"></div>';settings?.parentElement?.insertBefore(section,settings);}if(!document.querySelector('.nav-item[data-view="signals"]')){const settingsBtn=document.querySelector('.nav-item[data-view="settings"]'),btn=document.createElement("button");btn.className="nav-item";btn.dataset.view="signals";btn.setAttribute("aria-label","Signals");btn.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 17l5-5 4 3 7-8M17 7h3v3"/></svg><span>Signals</span>';settingsBtn?.parentElement?.insertBefore(btn,settingsBtn);btn.addEventListener("click",()=>show("signals"));}const nav=document.querySelector(".bottom-nav");if(nav)nav.style.gridTemplateColumns="repeat(5,1fr)";const rb=document.getElementById("signalsRefresh");if(rb&&!rb.dataset.bound){rb.dataset.bound="1";rb.addEventListener("click",()=>refresh(true));}}
  function show(name){document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===name));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${name}`));window.scrollTo({top:0,behavior:"auto"});if(name==="signals")refresh(false);}
  async function fetchData(force=false){const w=worker();if(w){try{const u=`${w}${w.includes("?")?"&":"?"}${force?"fresh=1&":""}signals=${Date.now()}`,r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}catch(e){console.warn("Signals Worker unavailable; using backup",e)}}const r=await fetch(`${GITHUB}?signals=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json();}
  function effective(key,side){const buy=side==="buy",label=buy?"BUY":"SELL",s=data?.signals?.[key];if(!s)return{side,status:"no-signal",action:`NO ${label} LIMIT SIGNAL`,confidenceScore:0,blockers:["No current live signal snapshot."]};const blockers=[...(s.blockers||[])],marketAge=ageMin(s.marketObservedAt||data?.technical?.observedAt),signalAge=ageMin(s.generatedAt||data?.signals?.generatedAt);if(marketAge>10)blockers.unshift(`Market data is ${Math.floor(marketAge)} minutes old — refresh required.`);if(signalAge>10)blockers.unshift(`Signal snapshot is ${Math.floor(signalAge)} minutes old — refresh required.`);if(s.validUntil&&Date.now()>new Date(s.validUntil).getTime())blockers.unshift("Signal expired — recalculate before using it.");const ok=s.status==="candidate"&&blockers.length===0;return{...s,side,status:ok?"candidate":"no-signal",action:ok?`${label} LIMIT CANDIDATE`:`NO ${label} LIMIT SIGNAL`,confidenceScore:ok?(s.confidenceScore??0):0,blockers};}
  function signalCard(s,side){const buy=side==="buy",ok=s.status==="candidate",layers=s.layers||{},word=buy?"buy":"sell";return`<section class="gms-signal ${buy?"buy":"sell"} ${ok?"go":"stop"}"><span class="eyebrow">${buy?"BUY-SIDE":"SELL-SIDE"} SETUP</span><h2>${esc(s.action)}</h2><p>${ok?`Every strict ${word}-limit gate currently passes. Refresh again immediately before placing a pending order.`:`No ${word} limit is promoted while any freshness, macro, structure, order-block, news-risk or R:R gate fails.`}</p><div class="gms-grid"><div><span>XAUUSD</span><strong>${s.currentPrice??"—"}</strong></div><div><span>Conviction</span><strong>${s.confidenceScore??0}/100</strong></div><div><span>Macro</span><strong>${signed(s.macroScore)}</strong></div><div><span>Agreement</span><strong>${s.macroAgreementPct??0}%</strong></div></div>${ok?`<div class="gms-plan ${buy?"buy":"sell"}"><span class="eyebrow">${buy?"BUY":"SELL"} LIMIT PLAN</span><h3>${s.entryZoneLow} – ${s.entryZoneHigh}</h3><div class="gms-levels"><div><span>${buy?"Buy":"Sell"} limit</span><strong>${s.limitPrice}</strong></div><div><span>SL</span><strong>${s.stopLossReference}</strong></div><div><span>TP1</span><strong>${s.tp1Reference}</strong><small>${s.rrTp1}R</small></div><div><span>TP2</span><strong>${s.tp2Reference}</strong><small>${s.rrTp2}R</small></div></div><p>Order-block quality ${s.orderBlockQuality}/100. These are planning references, not guaranteed outcomes.</p></div>`:""}<div class="gms-mini"><span>48h <b>${signed(layers.fresh)}</b></span><span>7-day <b>${signed(layers.weekly)}</b></span><span>90-day CPI/Fed <b>${signed(layers.regime)}</b></span><span>USD/yields/XAU <b>${signed(layers.market)}</b></span></div>${s.blockers?.length?`<div class="gms-block"><strong>Why ${word} is blocked</strong><ul>${s.blockers.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>`:""}</section>`;}
  function render(){installUI();const panel=document.getElementById("signalsPanel");if(!panel)return;const buy=effective("buyLimit","buy"),sell=effective("sellLimit","sell"),next=buy.nextEvent||sell.nextEvent,observed=buy.marketObservedAt||sell.marketObservedAt||data?.technical?.observedAt,calculated=data?.signals?.generatedAt||buy.generatedAt||sell.generatedAt,trueLive=data?.collectorMode==="cloudflare-true-live"||data?.sourceStatus?.worker==="true-live";panel.innerHTML=`<section class="gms-card"><span class="eyebrow">${trueLive?"TRUE LIVE SOURCE":"BACKUP SOURCE"}</span><h3>${trueLive?"OANDA + macro/news refreshed directly":"Waiting for live Worker"}</h3><p>${trueLive?"Signals use the same fresh request as price, 4H/D candles, calendar and news.":"Signals remain freshness-gated and will not be promoted from stale backup data."}</p></section>${signalCard(buy,"buy")}${signalCard(sell,"sell")}<section class="gms-card"><span class="eyebrow">FRESHNESS</span><div class="gms-fresh"><div><span>OANDA observed</span><strong>${fmt(observed)}</strong><small>${Math.floor(ageMin(observed))} min old</small></div><div><span>Signals calculated</span><strong>${fmt(calculated)}</strong><small>${Math.floor(ageMin(calculated))} min old</small></div></div></section><section class="gms-card"><span class="eyebrow">NEXT NEWS RISK</span><h3>${next?esc(next.name):"No upcoming medium/high-impact event loaded"}</h3><p>${next?`${fmt(next.dateUtc)} · about ${next.minutesAway} min away`:"Freshness and technical invalidation gates still apply."}</p></section><p class="gms-disclaimer">No setup can be guaranteed safe or profitable. Gold Mine blocks stale, conflicting or weak setups rather than forcing a signal.</p>`;}
  async function refresh(force){if(busy)return;busy=true;installUI();const b=document.getElementById("signalsRefresh");if(b){b.disabled=true;b.textContent=force?"Refreshing OANDA + news…":"Checking…";}try{data=await fetchData(force);sessionStorage.setItem("goldmine-last-check-at",new Date().toISOString());render();const buy=effective("buyLimit","buy"),sell=effective("sellLimit","sell"),live=data?.collectorMode==="cloudflare-true-live"||data?.sourceStatus?.worker==="true-live";if(b)b.textContent=live?(buy.status==="candidate"||sell.status==="candidate"?"Live signal ✓":"Live · no setup"):"Backup loaded";window.dispatchEvent(new CustomEvent("goldmine-signals-updated",{detail:data}));}catch(e){console.warn("Signals refresh failed",e);if(b)b.textContent="Refresh failed";}finally{busy=false;if(b){b.disabled=false;setTimeout(()=>{if(!busy)b.textContent="Refresh signals live";},2200)}}}
  function style(){if(document.getElementById("gms-style"))return;const s=document.createElement("style");s.id="gms-style";s.textContent=`.gms-card,.gms-signal{background:#fff;border:1px solid #e5e1d8;border-radius:18px;padding:15px;margin-bottom:12px}.gms-card h3,.gms-signal h2{margin:5px 0}.gms-card p,.gms-signal p{font-size:11px;color:#666d76;line-height:1.45}.gms-signal{border-left:6px solid #c8c5bd}.gms-signal.buy.go{border-left-color:#247a52}.gms-signal.sell.go{border-left-color:#b43a3a}.gms-signal.buy.go h2{color:#247a52}.gms-signal.sell.go h2{color:#b43a3a}.gms-signal.stop h2{color:#6f747c}.gms-grid,.gms-levels,.gms-fresh{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.gms-fresh{grid-template-columns:1fr 1fr}.gms-grid>div,.gms-levels>div,.gms-fresh>div{background:#f7f6f2;border-radius:11px;padding:10px}.gms-grid span,.gms-levels span,.gms-fresh span{display:block;font-size:9px;color:#777;text-transform:uppercase}.gms-grid strong,.gms-levels strong,.gms-fresh strong{display:block;margin-top:4px;font-size:13px}.gms-levels small,.gms-fresh small{display:block;font-size:9px;color:#777;margin-top:2px}.gms-plan{border-radius:13px;padding:12px;margin-top:12px;background:#fbfbf8}.gms-plan.buy{border-left:4px solid #247a52}.gms-plan.sell{border-left:4px solid #b43a3a}.gms-mini{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.gms-mini span{font-size:9px;background:#f4f3ef;border-radius:999px;padding:5px 7px;color:#70757d}.gms-block{margin-top:11px;padding:10px 11px;background:#fff9f8;border:1px solid #efd4d1;border-radius:12px}.gms-block li{font-size:10.5px;line-height:1.4;margin:5px 0;color:#684a48}.gms-disclaimer{font-size:9px;color:#7c828a;line-height:1.45;margin:8px 2px 0}@media(max-width:700px){.gms-grid,.gms-levels{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
  function boot(){style();installUI();document.addEventListener("visibilitychange",()=>{if(!document.hidden&&active())refresh(false)});window.addEventListener("goldmine-snapshot-updated",e=>{if(e.detail){data=e.detail;render()}});setTimeout(()=>refresh(false),250);clearInterval(timer);timer=setInterval(()=>{if(!document.hidden&&active())refresh(false)},15000)}
  boot();
})();
